### ISSUE TITLE
Cannot start dcvviewer as non-root user

### ISSUE THREAD

**Issue by kanwarplaha** [awsdocs/nice-dcv-user-guide#2]
When running dcvviewer on Linux, as an unprivileged user, the following error is thrown:

`❯ dcvviewer
thread '<unnamed>' panicked at 'GTK has to be initialized first', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.15.5/src/subclass/widget.rs:1032:13`
`note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
`fatal runtime error: failed to initiate panic, error 5`
`/usr/bin/dcvviewer: line 41:  7172 Aborted                 (core dumped) "${dcvviewer_bin}" "$@"`

However, it runs at root (or sudo) but I don't want to run it as such.

**Comment by kanwarplaha** [comment]
Running with `RUST_BACKTRACE=1` and `RUST_BACKTRACE=full` ...

❯ RUST_BACKTRACE=1 dcvviewer
thread '<unnamed>' panicked at 'GTK has to be initialized first', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.15.5/src/subclass/widget.rs:1032:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/usr/bin/dcvviewer: line 41:  8375 Aborted                 (core dumped) "${dcvviewer_bin}" "$@"
❯ RUST_BACKTRACE=full dcvviewer
thread '<unnamed>' panicked at 'GTK has to be initialized first', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.15.5/src/subclass/widget.rs:1032:13
stack backtrace:
   0:     0x7f474e167280 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
   1:     0x7f474e1c0f2e - core::fmt::write::hd5207aebbb9a86e9
   2:     0x7f474e158605 - <unknown>
   3:     0x7f474e169f33 - <unknown>
   4:     0x7f474e169c1f - std::panicking::default_hook::haa3ca8c310ed5402
   5:     0x7f474e16a66a - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
   6:     0x7f474e16a521 - <unknown>
   7:     0x7f474e16772c - <unknown>
   8:     0x7f474e16a282 - rust_begin_unwind
   9:     0x7f474db016f3 - core::panicking::panic_fmt::h8d17ca1073d9a733
  10:     0x55a9c4a6f207 - <unknown>
  11:     0x55a9c4ae400d - <unknown>
  12:     0x55a9c4add8f1 - <unknown>
  13:     0x7f474ca3b0b2 - g_type_class_ref
  14:     0x7f4747cc8144 - <unknown>
  15:     0x7f4747cc8200 - <unknown>
  16:     0x7f4747cc82ab - <unknown>
  17:     0x7f4747cc681a - gtk_module_init
  18:     0x7f474be6cc17 - <unknown>
  19:     0x7f474be6cdf8 - <unknown>
  20:     0x7f474bee17dd - <unknown>
  21:     0x7f474842009b - <unknown>
  22:     0x7f47484203ed - gtk_module_init
  23:     0x7f474be69d51 - <unknown>
  24:     0x7f474ca15f23 - g_closure_invoke
  25:     0x7f474ca295ee - <unknown>
  26:     0x7f474ca33658 - g_signal_emit_valist
  27:     0x7f474ca34002 - g_signal_emit
  28:     0x7f474ca1a1d4 - <unknown>
  29:     0x7f474ca1c6f9 - g_object_notify
  30:     0x7f474cd30e33 - <unknown>
  31:     0x7f474ca1613c - <unknown>
  32:     0x7f474ca33b16 - g_signal_emit_valist
  33:     0x7f474ca3449a - g_signal_emit_by_name
  34:     0x7f474cd62115 - <unknown>
  35:     0x7f474cd311c6 - gdk_display_manager_open_display
  36:     0x7f474be4bd68 - gtk_init_check
  37:     0x7f474be4bda9 - gtk_init
  38:     0x7f474bd21798 - <unknown>
  39:     0x55a9c4a564d9 - <unknown>
  40:     0x7f474ca1613c - <unknown>
  41:     0x7f474ca33b16 - g_signal_emit_valist
  42:     0x7f474ca34002 - g_signal_emit
  43:     0x7f474c6e0bf2 - g_application_register
  44:     0x7f474c6e0fa5 - <unknown>
  45:     0x7f474c6e12f6 - g_application_run
  46:     0x55a9c4a55489 - <unknown>
  47:     0x7f474ba2c5b0 - __libc_start_call_main
  48:     0x7f474ba2c679 - __libc_start_main@GLIBC_2.2.5
  49:     0x55a9c4a554ca - _start
  50:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
/usr/bin/dcvviewer: line 41:  8394 Aborted                 (core dumped) "${dcvviewer_bin}" "$@"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
